// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: exercises.sql

package db

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (
  name, sets, reps, routine_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, sets, reps, created_at, routine_id
`

type CreateExerciseParams struct {
	Name      string `json:"name"`
	Sets      int16  `json:"sets"`
	Reps      int16  `json:"reps"`
	RoutineID int32  `json:"routine_id"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.Name,
		arg.Sets,
		arg.Reps,
		arg.RoutineID,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sets,
		&i.Reps,
		&i.CreatedAt,
		&i.RoutineID,
	)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercises
WHERE id = $1
`

func (q *Queries) DeleteExercise(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteExercise, id)
	return err
}

const getExercise = `-- name: GetExercise :one
SELECT id, name, sets, reps, created_at, routine_id FROM exercises
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExercise(ctx context.Context, id int32) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sets,
		&i.Reps,
		&i.CreatedAt,
		&i.RoutineID,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, name, sets, reps, created_at, routine_id FROM exercises
ORDER BY name
`

func (q *Queries) ListExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sets,
			&i.Reps,
			&i.CreatedAt,
			&i.RoutineID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutineExercises = `-- name: ListRoutineExercises :many
SELECT id, name, sets, reps, created_at, routine_id FROM exercises
WHERE routine_id = $1
ORDER BY name
`

func (q *Queries) ListRoutineExercises(ctx context.Context, routineID int32) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listRoutineExercises, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sets,
			&i.Reps,
			&i.CreatedAt,
			&i.RoutineID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :exec
UPDATE exercises
  set name = $2,
      sets = $3,
      reps = $4,
      routine_id = $5
WHERE id = $1
RETURNING id, name, sets, reps, created_at, routine_id
`

type UpdateExerciseParams struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Sets      int16  `json:"sets"`
	Reps      int16  `json:"reps"`
	RoutineID int32  `json:"routine_id"`
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) error {
	_, err := q.db.Exec(ctx, updateExercise,
		arg.ID,
		arg.Name,
		arg.Sets,
		arg.Reps,
		arg.RoutineID,
	)
	return err
}
