// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Sets      int16            `json:"sets"`
	Reps      int16            `json:"reps"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	RoutineID int32            `json:"routine_id"`
}

type Routine struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
