// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	DeleteExercise(ctx context.Context, id int32) error
	GetExercise(ctx context.Context, id int32) (Exercise, error)
	ListExercises(ctx context.Context) ([]Exercise, error)
	UpdateExercise(ctx context.Context, arg UpdateExerciseParams) error
}

var _ Querier = (*Queries)(nil)
