FROM golang:1.22-alpine

WORKDIR /app

COPY . .

RUN go get -d ./...
RUN go install github.com/pressly/goose/v3/cmd/goose@latest && \
    go install github.com/cosmtrek/air@latest && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
               
CMD ["go", "run", "main.go"]
